### ISSUE TITLE
Lightning Experience Reports and Dashboards Specialist

### ISSUE THREAD

**Issue by shunkosa** [shunkosa/trailhead-superbadge-jp#1]
- [x] Prenote
- [x] Challenge 1
- [x] Challenge 2
- [x] Challenge 3
- [x] Challenge 4
- [x] Challenge 5
- [x] Challenge 6
- [x] Challenge 7
- [x] Challenge 8

**Comment by Karthikeyans03** [comment]
Share the solution

**Comment by shunkosa** [comment]
@Karthikeyans03 Sorry, this repo is just for localization of superbadge content.
