### ISSUE TITLE
Einstein Analytics Insight Specialist

### ISSUE THREAD

**Issue by shunkosa** [shunkosa/trailhead-superbadge-jp#12]
- [x] Header
- [x] Prework and Notes
- [x] Scenario
- [x] Objects
- [x] External Files
- [ ] Calculate Subscriber Churn Rate
- [ ] Display Churn by Tenure
- [x] Calculate Subscriber Acquisition Costs
- [x] Compare Churn to Subscriber CSATs
- [x] Deliver a Solution to Reduce Subscriber Attrition
- [x] Challenge

**Comment by shunkosa** [comment]
Published

**Comment by umrakhan408** [comment]
hy can i get churn by tenure solution

**Comment by shunkosa** [comment]
Sorry this project is just localization and cannot provide solution
