### ISSUE TITLE
Challenge Not yet complete... here's what's wrong:  We can't find the 'Team Roles Related List'. Ensure you add a way for agents to customize who is assigned to each role for each case.

### ISSUE THREAD

**Issue by GaurangDeshpande012** [shunkosa/trailhead-superbadge-jp#16]

**Comment by shunkosa** [comment]
@GaurangDeshpande012 Thank you for reaching out! Is it still unresolved? Make sure that you set up case team and put the related list on the layout.

**Comment by shunkosa** [comment]
I'll close this issue. Please feel free to ask me if you need help further.
