### ISSUE TITLE
Service Cloud Specialist

### ISSUE THREAD

**Issue by shunkosa** [shunkosa/trailhead-superbadge-jp#2]
- [x] Prenote
- [x] Challenge 1
- [x] Challenge 2
- [x] Challenge 3
- [x] Challenge 4
- [x] Challenge 5
- [x] Challenge 6
- [x] Challenge 7

**Comment by AshishManuka** [comment]
Can You Please Provide the notes So we Can Follow That And Solve Superbadge

**Comment by vasavimallika** [comment]
Can You Please Provide the notes So we Can Follow That And Solve Superbadge
