### ISSUE TITLE
App Customization Specialistのレポートタイプ名について

### ISSUE THREAD

**Issue by YoheiIchikawa** [shunkosa/trailhead-superbadge-jp#28]
いつもありがとうございます！
表題の件ですが、2つ目のレポートタイプの名前が元の名前と違いましたのでご確認お願いします！

×：Accounts with Volunteer Activities with Volunteer Jobs
〇：Accounts with Vol Activities with Vol Jobs

**Comment by shunkosa** [comment]
@YoheiIchikawa お知らせありがとうございます！修正いたしました。本当に助かります！Superbadgeもリリースノートが欲しいですね…。
https://github.com/shunkosa/trailhead-superbadge-jp/commit/0188c58b3835ab2a389d6708549515e1c016db44

**Comment by YoheiIchikawa** [comment]
@shunkosa 
早速のご対応ありがとうございます！
READMEに名前まで載せていただいてありがとうございます。
Superbadgeのリリースノートいいですね！変更されたら何かしらアナウンスほしいですねー
