### ISSUE TITLE
Lightning Experience Reports & Dashboards Specialistについて

### ISSUE THREAD

**Issue by YoheiIchikawa** [shunkosa/trailhead-superbadge-jp#29]
いつもお世話になっています！
表題の件、細かい事で申し訳ないですが2点ご確認お願いします。

１．Superbadgeのタイトルの「Experience」が抜けている箇所が何か所かありました。READMEの中と、Webサイト版の左の目次部分です。文字数が多いからあえて抜いているという事だったら申し訳ありません。
　Lightning Reports and Dashboards Specialist
　↓
　Lightning Experience Reports & Dashboards Specialist
　　
２．「分析結果をより見やすく便利にする」の「3.」の最初の文の「、」の直後、「your users」の訳が抜けているようです。

**Comment by shunkosa** [comment]
いつもありがとうございます！修正しました！

**Comment by YoheiIchikawa** [comment]
早速のご対応ありがとうございます！
今後も活用させていただきます！
