### ISSUE TITLE
管理パッケージのIDについて

### ISSUE THREAD

**Issue by YoheiIchikawa** [shunkosa/trailhead-superbadge-jp#30]
いつもお世話になっています！
特定のSuperbadgeではなく、全体的な話です。

ほとんどのSuperbadgeでは最初に管理パッケージのインストールが必要になると思いますが、その際に必要となる「パッケージID」も載せていただく事はできますでしょうか。
最近のPlaygroundでは管理パッケージのインストールの際はURLをいろいろ加工するのではなく、「Playground Starter」アプリケーションでパッケージIDを入力してインストールしますので、パッケージIDが載っていると非常に助かります。

また、管理パッケージのインストール手順に関する「この記事」のリンク先が変わっていますので、こちらもご確認いただけますでしょうか。上記の「Playground Starter」アプリケーションを使用した手順のページへのリンクに変わっていました。
https://trailhead.salesforce.com/ja/help?article=Installing-a-package-or-app-to-complete-a-Trailhead-challenge

**Comment by shunkosa** [comment]
更新しました！

**Comment by YoheiIchikawa** [comment]
ご対応ありがとうございます！
次もまた活用させていただきます！
