### ISSUE TITLE
Lightning Web Component Specialist

### ISSUE THREAD

**Issue by shunkosa** [shunkosa/trailhead-superbadge-jp#36]
- [x] What You'll Be Doing to Earn This Superbadge
- [x] Concepts Tested in This Superbadge
- [x] Prework and Notes
- [x] Use case
- [x] Key Stakeholders and Team
- [x] Standard Objects
- [x] Custom Objects
- [x] Entity Diagram
- [x] Application Design
- [x] Build the Boat Message Service Channel
- [x] Let’s Sail Away!
- [x] Build the Gallery
- [x] Show the Boats on a Map
- [x] Display Nearby Boats!
- [x] Integrate Third-Party Scripts
- [x] Add Reviews to the Boats
- [x] Convert the Similar Boats Page to Lightning
- [x] Challenges
- [x] Tips

**Comment by avdhesh0521** [comment]
Build the Boat Message Service channel i need the solution
