### ISSUE TITLE
Copy & Paste miss: Retalor <- Realtor

### ISSUE THREAD

**Issue by az-ak** [shunkosa/trailhead-superbadge-jp#42]
fsc-specialist にコピペミスがありました。

翻訳：関連ロールは、**Retalor** (Torres-Adams Household から見て) と Customer (Caroline Kane - Lakeshore Realty から見て) としてください。

原文：The related role should be **Realtor** with Customer as the inverse role.

RetalorではなくRealtorです。（多分Challengeでチェックされる部分なので。）
翻訳大変に助かっております。

**Comment by shunkosa** [comment]
@az-ak ご報告ありがとうございます！！修正いたしました。at https://github.com/shunkosa/trailhead-superbadge-jp/commit/d24442d776e113e28e63bcf428aebf3305115e06
