### ISSUE TITLE
修正提案

### ISSUE THREAD

**Issue by markhammer** [shunkosa/trailhead-superbadge-jp#9]
日本語訳お疲れ様です。
以下について修正を提案いたします。
お手数ですがご確認いただけますと幸いです。

# Service Cloud Specialist
## Challenge 1: エージェントのサポートユーザインタフェース

本文では
>To help with testing and user acceptance, add a login for Ada and provide her with the Cloud Team Technical Support profile.

と、具体的に**Cloud Team Technical Support**プロファイルへの適用を記載しているので、そのまま訳した方が良いと思います。

## Challenge 6: エージェントの活動の自動化

Cloudy weatherはメールアドレスではないので、 **Reusable email name** は「再利用可能なメール名」でいいと思います。

>Close out the case, adding the Cloudy weather response sent reusable text to the description.

については、作成した再利用可能なテキストを使用することを重視した文言に修正したほうが良いと思います。

## Challenge 7: コンタクトセンターの分析

縦棒グラフについてはCloud Support Reports、Case Performance Dashboardいずれも英語本文では出てきませんが、Case Performance Dashboardで記載するのであればCloud Support Reports側でも記載してあげるのが親切かと思いました。
※Cloud Support Reportsが横棒グラフではクリアできないことは確認済です。

# Lightning Experience Rollout Specialist
### Challenge 6
Group_Recourd_Page -> Group_Record_Page

# Security Specialist
## Challenge 2: 項目レベルのセキュリティ設定
Needs Analysys -> Needs Analysis

**Comment by shunkosa** [comment]
いずれも確認しマージ済しました。凡ミスすみません…。ありがとうございました。
